"""ThreatLocker MCP tools for tag: ActionLog.

Generated by scripts/generate_from_spec.py. Do not edit by hand.
"""
from __future__ import annotations

from typing import Annotated, Any, Optional

from fastmcp import FastMCP
from pydantic import Field

from ..client import get_client
from .. import models


def register(mcp: FastMCP) -> None:
    @mcp.tool(name="action_log_get_by_parameters_v2", description="Get Action Logs By Parameters. NOTE: the API requires the date range supplied in BOTH `dateTime` (array of two ISO 8601 strings) AND `startDate`/`endDate` -- passing only one returns 417 'Invalid Date")
    async def action_log_get_by_parameters_v2(
        body: Annotated[models.ActionLogParamsDto, Field(description="Request body.")],
        usenewsearch: Annotated[Optional[str], Field(description="Header: usenewsearch", default=None)] = None,
        organization_id: Annotated[Optional[str], Field(description="Override the default organization (ManagedOrganizationId header).", default=None)] = None,
        override_organization_id: Annotated[Optional[str], Field(description="Optional OverrideManagedOrganizationId header.", default=None)] = None,
    ) -> Any:
        """Get Action Logs By Parameters. NOTE: the API requires the date range supplied in BOTH `dateTime` (array of two ISO 8601 strings) AND `startDate`/`endDate` -- passing only one returns 417 'Invalid Date Range' or HTTP 500."""
        body_json = body.model_dump(by_alias=True, exclude_none=True)
        extra_headers = {}
        if override_organization_id is not None:
            extra_headers['OverrideManagedOrganizationId'] = override_organization_id
        if usenewsearch is not None:
            extra_headers['usenewsearch'] = usenewsearch
        client = await get_client()
        return await client.request("POST", "/portalapi/ActionLog/ActionLogGetByParametersV2", organization_id=organization_id, json=body_json, extra_headers=extra_headers or None)


    @mcp.tool(name="action_log_get_by_id_v2", description='GET /portalapi/ActionLog/ActionLogGetByIdV2')
    async def action_log_get_by_id_v2(
        e_action_log_id: Annotated[Optional[str], Field(default=None)] = None,
        source_table_id: Annotated[Optional[int], Field(default=None)] = None,
        add_to_application: Annotated[Optional[bool], Field(default=None)] = None,
        get_all_parents: Annotated[Optional[bool], Field(default=None)] = None,
        opened_from_link: Annotated[Optional[bool], Field(default=None)] = None,
        organization_id: Annotated[Optional[str], Field(description="Override the default organization (ManagedOrganizationId header).", default=None)] = None,
        override_organization_id: Annotated[Optional[str], Field(description="Optional OverrideManagedOrganizationId header.", default=None)] = None,
    ) -> Any:
        """GET /portalapi/ActionLog/ActionLogGetByIdV2"""
        params = {"eActionLogId": e_action_log_id, "sourceTableId": source_table_id, "addToApplication": add_to_application, "getAllParents": get_all_parents, "openedFromLink": opened_from_link}
        params = {k: v for k, v in params.items() if v is not None}
        extra_headers = {}
        if override_organization_id is not None:
            extra_headers['OverrideManagedOrganizationId'] = override_organization_id
        client = await get_client()
        return await client.request("GET", "/portalapi/ActionLog/ActionLogGetByIdV2", organization_id=organization_id, params=params, extra_headers=extra_headers or None)


    @mcp.tool(name="action_log_get_all_for_file_history_v2", description='Get All File History by hostname and fullpath')
    async def action_log_get_all_for_file_history_v2(
        source_table_id: Annotated[Optional[int], Field(default=None)] = None,
        hostname: Annotated[Optional[str], Field(default=None)] = None,
        full_path: Annotated[Optional[str], Field(default=None)] = None,
        computer_id: Annotated[Optional[str], Field(default=None)] = None,
        page_number: Annotated[Optional[int], Field(default=None)] = None,
        page_size: Annotated[Optional[int], Field(default=None)] = None,
        organization_id: Annotated[Optional[str], Field(description="Override the default organization (ManagedOrganizationId header).", default=None)] = None,
        override_organization_id: Annotated[Optional[str], Field(description="Optional OverrideManagedOrganizationId header.", default=None)] = None,
    ) -> Any:
        """Get All File History by hostname and fullpath"""
        params = {"sourceTableId": source_table_id, "hostname": hostname, "fullPath": full_path, "computerId": computer_id, "pageNumber": page_number, "pageSize": page_size}
        params = {k: v for k, v in params.items() if v is not None}
        extra_headers = {}
        if override_organization_id is not None:
            extra_headers['OverrideManagedOrganizationId'] = override_organization_id
        client = await get_client()
        return await client.request("GET", "/portalapi/ActionLog/ActionLogGetAllForFileHistoryV2", organization_id=organization_id, params=params, extra_headers=extra_headers or None)


    @mcp.tool(name="action_log_get_file_download_details_by_id", description='GET /portalapi/ActionLog/ActionLogGetFileDownloadDetailsById')
    async def action_log_get_file_download_details_by_id(
        e_action_log_id: Annotated[Optional[str], Field(default=None)] = None,
        source_table_id: Annotated[Optional[int], Field(default=None)] = None,
        organization_id: Annotated[Optional[str], Field(description="Override the default organization (ManagedOrganizationId header).", default=None)] = None,
        override_organization_id: Annotated[Optional[str], Field(description="Optional OverrideManagedOrganizationId header.", default=None)] = None,
    ) -> Any:
        """GET /portalapi/ActionLog/ActionLogGetFileDownloadDetailsById"""
        params = {"eActionLogId": e_action_log_id, "sourceTableId": source_table_id}
        params = {k: v for k, v in params.items() if v is not None}
        extra_headers = {}
        if override_organization_id is not None:
            extra_headers['OverrideManagedOrganizationId'] = override_organization_id
        client = await get_client()
        return await client.request("GET", "/portalapi/ActionLog/ActionLogGetFileDownloadDetailsById", organization_id=organization_id, params=params, extra_headers=extra_headers or None)

