"""ThreatLocker MCP tools for tag: Application.

Generated by scripts/generate_from_spec.py. Do not edit by hand.
"""

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import FastMCP
from pydantic import Field

from .. import models
from ..client import get_client


def register(mcp: FastMCP) -> None:
    @mcp.tool(name="application_get_by_id", description="Get Application by Id.")
    async def application_get_by_id(
        application_id: Annotated[str | None, Field(default=None)] = None,
        organization_id: Annotated[
            str | None,
            Field(
                description="Override the default organization (ManagedOrganizationId header).",
                default=None,
            ),
        ] = None,
        override_organization_id: Annotated[
            str | None,
            Field(description="Optional OverrideManagedOrganizationId header.", default=None),
        ] = None,
    ) -> Any:
        """Get Application by Id."""
        params = {"applicationId": application_id}
        params = {k: v for k, v in params.items() if v is not None}
        extra_headers = {}
        if override_organization_id is not None:
            extra_headers["OverrideManagedOrganizationId"] = override_organization_id
        client = await get_client()
        return await client.request(
            "GET",
            "/portalapi/Application/ApplicationGetById",
            organization_id=organization_id,
            params=params,
            extra_headers=extra_headers or None,
        )

    @mcp.tool(name="application_get_matching_list", description="Get Matching Applications")
    async def application_get_matching_list(
        body: Annotated[models.ApplicationMatchParameterDto, Field(description="Request body.")],
        organization_id: Annotated[
            str | None,
            Field(
                description="Override the default organization (ManagedOrganizationId header).",
                default=None,
            ),
        ] = None,
        override_organization_id: Annotated[
            str | None,
            Field(description="Optional OverrideManagedOrganizationId header.", default=None),
        ] = None,
    ) -> Any:
        """Get Matching Applications"""
        body_json = body.model_dump(by_alias=True, exclude_none=True)
        extra_headers = {}
        if override_organization_id is not None:
            extra_headers["OverrideManagedOrganizationId"] = override_organization_id
        client = await get_client()
        return await client.request(
            "POST",
            "/portalapi/Application/ApplicationGetMatchingList",
            organization_id=organization_id,
            json=body_json,
            extra_headers=extra_headers or None,
        )
