"""ThreatLocker MCP tools for tag: ApprovalRequest.

Generated by scripts/generate_from_spec.py. Do not edit by hand.
"""

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import FastMCP
from pydantic import Field

from .. import models
from ..client import get_client


def register(mcp: FastMCP) -> None:
    @mcp.tool(
        name="approval_request_get_by_parameters", description="Approval Request: Get By Parameters"
    )
    async def approval_request_get_by_parameters(
        body: Annotated[models.ApprovalRequestParametersDto, Field(description="Request body.")],
        organization_id: Annotated[
            str | None,
            Field(
                description="Override the default organization (ManagedOrganizationId header).",
                default=None,
            ),
        ] = None,
        override_organization_id: Annotated[
            str | None,
            Field(description="Optional OverrideManagedOrganizationId header.", default=None),
        ] = None,
    ) -> Any:
        """Approval Request: Get By Parameters"""
        body_json = body.model_dump(by_alias=True, exclude_none=True)
        extra_headers = {}
        if override_organization_id is not None:
            extra_headers["OverrideManagedOrganizationId"] = override_organization_id
        client = await get_client()
        return await client.request(
            "POST",
            "/portalapi/ApprovalRequest/ApprovalRequestGetByParameters",
            organization_id=organization_id,
            json=body_json,
            extra_headers=extra_headers or None,
        )

    @mcp.tool(name="approval_request_get_by_id", description="Get Approval Request By ID")
    async def approval_request_get_by_id(
        approval_request_id: Annotated[str | None, Field(default=None)] = None,
        organization_id: Annotated[
            str | None,
            Field(
                description="Override the default organization (ManagedOrganizationId header).",
                default=None,
            ),
        ] = None,
        override_organization_id: Annotated[
            str | None,
            Field(description="Optional OverrideManagedOrganizationId header.", default=None),
        ] = None,
    ) -> Any:
        """Get Approval Request By ID"""
        params = {"approvalRequestId": approval_request_id}
        params = {k: v for k, v in params.items() if v is not None}
        extra_headers = {}
        if override_organization_id is not None:
            extra_headers["OverrideManagedOrganizationId"] = override_organization_id
        client = await get_client()
        return await client.request(
            "GET",
            "/portalapi/ApprovalRequest/ApprovalRequestGetById",
            organization_id=organization_id,
            params=params,
            extra_headers=extra_headers or None,
        )

    @mcp.tool(name="approval_request_get_count", description="Get Approval Request Pending Count")
    async def approval_request_get_count(
        include_child_organizations: Annotated[bool | None, Field(default=None)] = None,
        organization_id: Annotated[
            str | None,
            Field(
                description="Override the default organization (ManagedOrganizationId header).",
                default=None,
            ),
        ] = None,
        override_organization_id: Annotated[
            str | None,
            Field(description="Optional OverrideManagedOrganizationId header.", default=None),
        ] = None,
    ) -> Any:
        """Get Approval Request Pending Count"""
        params = {"includeChildOrganizations": include_child_organizations}
        params = {k: v for k, v in params.items() if v is not None}
        extra_headers = {}
        if override_organization_id is not None:
            extra_headers["OverrideManagedOrganizationId"] = override_organization_id
        client = await get_client()
        return await client.request(
            "GET",
            "/portalapi/ApprovalRequest/ApprovalRequestGetCount",
            organization_id=organization_id,
            params=params,
            extra_headers=extra_headers or None,
        )

    @mcp.tool(
        name="approval_request_get_permit_application_by_id",
        description="Get Permit Application Details By Approval Request Id",
    )
    async def approval_request_get_permit_application_by_id(
        approval_request_id: Annotated[str | None, Field(default=None)] = None,
        organization_id: Annotated[
            str | None,
            Field(
                description="Override the default organization (ManagedOrganizationId header).",
                default=None,
            ),
        ] = None,
        override_organization_id: Annotated[
            str | None,
            Field(description="Optional OverrideManagedOrganizationId header.", default=None),
        ] = None,
    ) -> Any:
        """Get Permit Application Details By Approval Request Id"""
        params = {"approvalRequestId": approval_request_id}
        params = {k: v for k, v in params.items() if v is not None}
        extra_headers = {}
        if override_organization_id is not None:
            extra_headers["OverrideManagedOrganizationId"] = override_organization_id
        client = await get_client()
        return await client.request(
            "GET",
            "/portalapi/ApprovalRequest/ApprovalRequestGetPermitApplicationById",
            organization_id=organization_id,
            params=params,
            extra_headers=extra_headers or None,
        )

    @mcp.tool(
        name="approval_request_permit_application", description="Approve Permit Application Request"
    )
    async def approval_request_permit_application(
        body: Annotated[models.PermitApplicationDto, Field(description="Request body.")],
        organization_id: Annotated[
            str | None,
            Field(
                description="Override the default organization (ManagedOrganizationId header).",
                default=None,
            ),
        ] = None,
        override_organization_id: Annotated[
            str | None,
            Field(description="Optional OverrideManagedOrganizationId header.", default=None),
        ] = None,
    ) -> Any:
        """Approve Permit Application Request"""
        body_json = body.model_dump(by_alias=True, exclude_none=True)
        extra_headers = {}
        if override_organization_id is not None:
            extra_headers["OverrideManagedOrganizationId"] = override_organization_id
        client = await get_client()
        return await client.request(
            "POST",
            "/portalapi/ApprovalRequest/ApprovalRequestPermitApplication",
            organization_id=organization_id,
            json=body_json,
            extra_headers=extra_headers or None,
        )

    @mcp.tool(name="approval_request_update_for_reject", description="Reject Approval Request")
    async def approval_request_update_for_reject(
        body: Annotated[
            models.ApprovalRequestUpdateParametersDto, Field(description="Request body.")
        ],
        organization_id: Annotated[
            str | None,
            Field(
                description="Override the default organization (ManagedOrganizationId header).",
                default=None,
            ),
        ] = None,
        override_organization_id: Annotated[
            str | None,
            Field(description="Optional OverrideManagedOrganizationId header.", default=None),
        ] = None,
    ) -> Any:
        """Reject Approval Request"""
        body_json = body.model_dump(by_alias=True, exclude_none=True)
        extra_headers = {}
        if override_organization_id is not None:
            extra_headers["OverrideManagedOrganizationId"] = override_organization_id
        client = await get_client()
        return await client.request(
            "POST",
            "/portalapi/ApprovalRequest/ApprovalRequestUpdateForReject",
            organization_id=organization_id,
            json=body_json,
            extra_headers=extra_headers or None,
        )

    @mcp.tool(name="approval_request_update_for_ignore", description="Ignore Approval Request")
    async def approval_request_update_for_ignore(
        body: Annotated[
            models.ApprovalRequestUpdateParametersDto, Field(description="Request body.")
        ],
        organization_id: Annotated[
            str | None,
            Field(
                description="Override the default organization (ManagedOrganizationId header).",
                default=None,
            ),
        ] = None,
        override_organization_id: Annotated[
            str | None,
            Field(description="Optional OverrideManagedOrganizationId header.", default=None),
        ] = None,
    ) -> Any:
        """Ignore Approval Request"""
        body_json = body.model_dump(by_alias=True, exclude_none=True)
        extra_headers = {}
        if override_organization_id is not None:
            extra_headers["OverrideManagedOrganizationId"] = override_organization_id
        client = await get_client()
        return await client.request(
            "POST",
            "/portalapi/ApprovalRequest/ApprovalRequestUpdateForIgnore",
            organization_id=organization_id,
            json=body_json,
            extra_headers=extra_headers or None,
        )

    @mcp.tool(
        name="approval_request_update_for_take_ownership",
        description="Take Ownership of Approval Request",
    )
    async def approval_request_update_for_take_ownership(
        body: Annotated[models.ApprovalRequestDto, Field(description="Request body.")],
        organization_id: Annotated[
            str | None,
            Field(
                description="Override the default organization (ManagedOrganizationId header).",
                default=None,
            ),
        ] = None,
        override_organization_id: Annotated[
            str | None,
            Field(description="Optional OverrideManagedOrganizationId header.", default=None),
        ] = None,
    ) -> Any:
        """Take Ownership of Approval Request"""
        body_json = body.model_dump(by_alias=True, exclude_none=True)
        extra_headers = {}
        if override_organization_id is not None:
            extra_headers["OverrideManagedOrganizationId"] = override_organization_id
        client = await get_client()
        return await client.request(
            "POST",
            "/portalapi/ApprovalRequest/ApprovalRequestUpdateForTakeOwnership",
            organization_id=organization_id,
            json=body_json,
            extra_headers=extra_headers or None,
        )
