"""ThreatLocker MCP tools for tag: ComputerGroup.

Generated by scripts/generate_from_spec.py. Do not edit by hand.
"""

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import FastMCP
from pydantic import Field

from ..client import get_client


def register(mcp: FastMCP) -> None:
    @mcp.tool(
        name="computer_group_get_group_and_computer",
        description="Get Groups and Computer NOTE: this endpoint can return very large payloads (>100KB for a single populated group) when called without scoping. Pass a specific `computerGroupId` and set only the `include_*` flags you actually need; unscoped calls may exceed downstream output limits.",
    )
    async def computer_group_get_group_and_computer(
        computer_group_id: Annotated[str | None, Field(default=None)] = None,
        o_s_type: Annotated[int | None, Field(default=None)] = None,
        include_global: Annotated[bool | None, Field(default=None)] = None,
        include_all_policies: Annotated[bool | None, Field(default=None)] = None,
        include_organizations: Annotated[bool | None, Field(default=None)] = None,
        include_all_computers: Annotated[bool | None, Field(default=None)] = None,
        include_parent_groups: Annotated[bool | None, Field(default=None)] = None,
        include_logged_in_objects: Annotated[bool | None, Field(default=None)] = None,
        include_dns_servers: Annotated[bool | None, Field(default=None)] = None,
        include_ingestors: Annotated[bool | None, Field(default=None)] = None,
        portal_module_type_id: Annotated[int | None, Field(default=None)] = None,
        include_access_devices: Annotated[bool | None, Field(default=None)] = None,
        include_removed_computers: Annotated[bool | None, Field(default=None)] = None,
        organization_id: Annotated[
            str | None,
            Field(
                description="Override the default organization (ManagedOrganizationId header).",
                default=None,
            ),
        ] = None,
        override_organization_id: Annotated[
            str | None,
            Field(description="Optional OverrideManagedOrganizationId header.", default=None),
        ] = None,
    ) -> Any:
        """Get Groups and Computer NOTE: this endpoint can return very large payloads (>100KB for a single populated group) when called without scoping. Pass a specific `computerGroupId` and set only the `include_*` flags you actually need; unscoped calls may exceed downstream output limits."""
        params = {
            "ComputerGroupId": computer_group_id,
            "OSType": o_s_type,
            "IncludeGlobal": include_global,
            "IncludeAllPolicies": include_all_policies,
            "IncludeOrganizations": include_organizations,
            "IncludeAllComputers": include_all_computers,
            "IncludeParentGroups": include_parent_groups,
            "IncludeLoggedInObjects": include_logged_in_objects,
            "IncludeDnsServers": include_dns_servers,
            "IncludeIngestors": include_ingestors,
            "PortalModuleTypeId": portal_module_type_id,
            "IncludeAccessDevices": include_access_devices,
            "IncludeRemovedComputers": include_removed_computers,
        }
        params = {k: v for k, v in params.items() if v is not None}
        extra_headers = {}
        if override_organization_id is not None:
            extra_headers["OverrideManagedOrganizationId"] = override_organization_id
        client = await get_client()
        return await client.request(
            "GET",
            "/portalapi/ComputerGroup/ComputerGroupGetGroupAndComputer",
            organization_id=organization_id,
            params=params,
            extra_headers=extra_headers or None,
        )

    @mcp.tool(
        name="computer_group_get_dropdown_by_organization_id",
        description="Get Computer Groups by OrganizationId",
    )
    async def computer_group_get_dropdown_by_organization_id(
        computer_group_o_s_type_id: Annotated[int | None, Field(default=None)] = None,
        computer_o_s_type: Annotated[str | None, Field(default=None)] = None,
        hide_globals: Annotated[bool | None, Field(default=None)] = None,
        organization_id: Annotated[
            str | None,
            Field(
                description="Override the default organization (ManagedOrganizationId header).",
                default=None,
            ),
        ] = None,
        override_organization_id: Annotated[
            str | None,
            Field(description="Optional OverrideManagedOrganizationId header.", default=None),
        ] = None,
    ) -> Any:
        """Get Computer Groups by OrganizationId"""
        params = {
            "computerGroupOSTypeId": computer_group_o_s_type_id,
            "computerOSType": computer_o_s_type,
            "hideGlobals": hide_globals,
        }
        params = {k: v for k, v in params.items() if v is not None}
        extra_headers = {}
        if override_organization_id is not None:
            extra_headers["OverrideManagedOrganizationId"] = override_organization_id
        client = await get_client()
        return await client.request(
            "GET",
            "/portalapi/ComputerGroup/ComputerGroupGetDropdownByOrganizationId",
            organization_id=organization_id,
            params=params,
            extra_headers=extra_headers or None,
        )
