"""ThreatLocker MCP tools for tag: Computer.

Generated by scripts/generate_from_spec.py. Do not edit by hand.
"""

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import FastMCP
from pydantic import Field

from .. import models
from ..client import get_client


def register(mcp: FastMCP) -> None:
    @mcp.tool(name="computer_get_by_all_parameters", description="Load Computers By All Parameters")
    async def computer_get_by_all_parameters(
        body: Annotated[models.ComputerParameterDto, Field(description="Request body.")],
        organization_id: Annotated[
            str | None,
            Field(
                description="Override the default organization (ManagedOrganizationId header).",
                default=None,
            ),
        ] = None,
        override_organization_id: Annotated[
            str | None,
            Field(description="Optional OverrideManagedOrganizationId header.", default=None),
        ] = None,
    ) -> Any:
        """Load Computers By All Parameters"""
        body_json = body.model_dump(by_alias=True, exclude_none=True)
        extra_headers = {}
        if override_organization_id is not None:
            extra_headers["OverrideManagedOrganizationId"] = override_organization_id
        client = await get_client()
        return await client.request(
            "POST",
            "/portalapi/Computer/ComputerGetByAllParameters",
            organization_id=organization_id,
            json=body_json,
            extra_headers=extra_headers or None,
        )

    @mcp.tool(name="computer_get_for_edit_by_id", description="Get Computer Information By Id.")
    async def computer_get_for_edit_by_id(
        computer_id: Annotated[str | None, Field(default=None)] = None,
        organization_id: Annotated[
            str | None,
            Field(
                description="Override the default organization (ManagedOrganizationId header).",
                default=None,
            ),
        ] = None,
        override_organization_id: Annotated[
            str | None,
            Field(description="Optional OverrideManagedOrganizationId header.", default=None),
        ] = None,
    ) -> Any:
        """Get Computer Information By Id."""
        params = {"computerId": computer_id}
        params = {k: v for k, v in params.items() if v is not None}
        extra_headers = {}
        if override_organization_id is not None:
            extra_headers["OverrideManagedOrganizationId"] = override_organization_id
        client = await get_client()
        return await client.request(
            "GET",
            "/portalapi/Computer/ComputerGetForEditById",
            organization_id=organization_id,
            params=params,
            extra_headers=extra_headers or None,
        )

    @mcp.tool(name="computer_update_for_edit", description="Update Computer")
    async def computer_update_for_edit(
        body: Annotated[models.ComputerUpdateDto, Field(description="Request body.")],
        organization_id: Annotated[
            str | None,
            Field(
                description="Override the default organization (ManagedOrganizationId header).",
                default=None,
            ),
        ] = None,
        override_organization_id: Annotated[
            str | None,
            Field(description="Optional OverrideManagedOrganizationId header.", default=None),
        ] = None,
    ) -> Any:
        """Update Computer"""
        body_json = body.model_dump(by_alias=True, exclude_none=True)
        extra_headers = {}
        if override_organization_id is not None:
            extra_headers["OverrideManagedOrganizationId"] = override_organization_id
        client = await get_client()
        return await client.request(
            "PATCH",
            "/portalapi/Computer/ComputerUpdateForEdit",
            organization_id=organization_id,
            json=body_json,
            extra_headers=extra_headers or None,
        )

    @mcp.tool(name="computer_enable_protection", description="Computer Enable Protection")
    async def computer_enable_protection(
        body: Annotated[models.ComputerEnableProtectionDto, Field(description="Request body.")],
        organization_id: Annotated[
            str | None,
            Field(
                description="Override the default organization (ManagedOrganizationId header).",
                default=None,
            ),
        ] = None,
        override_organization_id: Annotated[
            str | None,
            Field(description="Optional OverrideManagedOrganizationId header.", default=None),
        ] = None,
    ) -> Any:
        """Computer Enable Protection"""
        body_json = body.model_dump(by_alias=True, exclude_none=True)
        extra_headers = {}
        if override_organization_id is not None:
            extra_headers["OverrideManagedOrganizationId"] = override_organization_id
        client = await get_client()
        return await client.request(
            "POST",
            "/portalapi/Computer/ComputerEnableProtection",
            organization_id=organization_id,
            json=body_json,
            extra_headers=extra_headers or None,
        )

    @mcp.tool(name="computer_disable_protection", description="Disable Computer Protection")
    async def computer_disable_protection(
        body: Annotated[models.ComputerDisabledProtectionDto, Field(description="Request body.")],
        organization_id: Annotated[
            str | None,
            Field(
                description="Override the default organization (ManagedOrganizationId header).",
                default=None,
            ),
        ] = None,
        override_organization_id: Annotated[
            str | None,
            Field(description="Optional OverrideManagedOrganizationId header.", default=None),
        ] = None,
    ) -> Any:
        """Disable Computer Protection"""
        body_json = body.model_dump(by_alias=True, exclude_none=True)
        extra_headers = {}
        if override_organization_id is not None:
            extra_headers["OverrideManagedOrganizationId"] = override_organization_id
        client = await get_client()
        return await client.request(
            "POST",
            "/portalapi/Computer/ComputerDisableProtection",
            organization_id=organization_id,
            json=body_json,
            extra_headers=extra_headers or None,
        )

    @mcp.tool(
        name="computer_update_maintenance_mode",
        description="Updates a device's maintenance mode settings.",
    )
    async def computer_update_maintenance_mode(
        body: Annotated[
            models.ComputerUpdateMaintenanceModeDto, Field(description="Request body.")
        ],
        organization_id: Annotated[
            str | None,
            Field(
                description="Override the default organization (ManagedOrganizationId header).",
                default=None,
            ),
        ] = None,
        override_organization_id: Annotated[
            str | None,
            Field(description="Optional OverrideManagedOrganizationId header.", default=None),
        ] = None,
    ) -> Any:
        """Updates a device's maintenance mode settings."""
        body_json = body.model_dump(by_alias=True, exclude_none=True)
        extra_headers = {}
        if override_organization_id is not None:
            extra_headers["OverrideManagedOrganizationId"] = override_organization_id
        client = await get_client()
        return await client.request(
            "POST",
            "/portalapi/Computer/ComputerUpdateMaintenanceMode",
            organization_id=organization_id,
            json=body_json,
            extra_headers=extra_headers or None,
        )

    @mcp.tool(name="computer_move_to_other_organization", description="Move Computer")
    async def computer_move_to_other_organization(
        body: Annotated[models.ComputerTransferDto, Field(description="Request body.")],
        organization_id: Annotated[
            str | None,
            Field(
                description="Override the default organization (ManagedOrganizationId header).",
                default=None,
            ),
        ] = None,
        override_organization_id: Annotated[
            str | None,
            Field(description="Optional OverrideManagedOrganizationId header.", default=None),
        ] = None,
    ) -> Any:
        """Move Computer"""
        body_json = body.model_dump(by_alias=True, exclude_none=True)
        extra_headers = {}
        if override_organization_id is not None:
            extra_headers["OverrideManagedOrganizationId"] = override_organization_id
        client = await get_client()
        return await client.request(
            "POST",
            "/portalapi/Computer/ComputerMoveToOtherOrganization",
            organization_id=organization_id,
            json=body_json,
            extra_headers=extra_headers or None,
        )

    @mcp.tool(name="computer_update_baseline_rescan", description="Update Baseline Rescan Computer")
    async def computer_update_baseline_rescan(
        body: Annotated[models.ComputerRescanBaselineDto, Field(description="Request body.")],
        organization_id: Annotated[
            str | None,
            Field(
                description="Override the default organization (ManagedOrganizationId header).",
                default=None,
            ),
        ] = None,
        override_organization_id: Annotated[
            str | None,
            Field(description="Optional OverrideManagedOrganizationId header.", default=None),
        ] = None,
    ) -> Any:
        """Update Baseline Rescan Computer"""
        body_json = body.model_dump(by_alias=True, exclude_none=True)
        extra_headers = {}
        if override_organization_id is not None:
            extra_headers["OverrideManagedOrganizationId"] = override_organization_id
        client = await get_client()
        return await client.request(
            "POST",
            "/portalapi/Computer/ComputerUpdateBaselineRescan",
            organization_id=organization_id,
            json=body_json,
            extra_headers=extra_headers or None,
        )
