"""ThreatLocker MCP tools for tag: MaintenanceMode.

Generated by scripts/generate_from_spec.py. Do not edit by hand.
"""
from __future__ import annotations

from typing import Annotated, Any, Optional

from fastmcp import FastMCP
from pydantic import Field

from ..client import get_client
from .. import models


def register(mcp: FastMCP) -> None:
    @mcp.tool(name="maintenance_mode_get_by_computer_id", description='Get Maintenance Schedule By Computer Id')
    async def maintenance_mode_get_by_computer_id(
        computer_id: Annotated[Optional[str], Field(default=None)] = None,
        organization_id: Annotated[Optional[str], Field(description="Override the default organization (ManagedOrganizationId header).", default=None)] = None,
        override_organization_id: Annotated[Optional[str], Field(description="Optional OverrideManagedOrganizationId header.", default=None)] = None,
    ) -> Any:
        """Get Maintenance Schedule By Computer Id"""
        params = {"computerId": computer_id}
        params = {k: v for k, v in params.items() if v is not None}
        extra_headers = {}
        if override_organization_id is not None:
            extra_headers['OverrideManagedOrganizationId'] = override_organization_id
        client = await get_client()
        return await client.request("GET", "/portalapi/MaintenanceMode/MaintenanceModeGetByComputerId", organization_id=organization_id, params=params, extra_headers=extra_headers or None)


    @mcp.tool(name="maintenance_mode_insert", description='Add to Maintenance Schedule')
    async def maintenance_mode_insert(
        body: Annotated[models.MaintenanceModeInsertDto, Field(description="Request body.")],
        organization_id: Annotated[Optional[str], Field(description="Override the default organization (ManagedOrganizationId header).", default=None)] = None,
        override_organization_id: Annotated[Optional[str], Field(description="Optional OverrideManagedOrganizationId header.", default=None)] = None,
    ) -> Any:
        """Add to Maintenance Schedule"""
        body_json = body.model_dump(by_alias=True, exclude_none=True)
        extra_headers = {}
        if override_organization_id is not None:
            extra_headers['OverrideManagedOrganizationId'] = override_organization_id
        client = await get_client()
        return await client.request("POST", "/portalapi/MaintenanceMode/MaintenanceModeInsert", organization_id=organization_id, json=body_json, extra_headers=extra_headers or None)


    @mcp.tool(name="maintenance_mode_end_by_id", description='End Maintenance Schedule')
    async def maintenance_mode_end_by_id(
        body: Annotated[models.MaintenanceModeEndDto, Field(description="Request body.")],
        organization_id: Annotated[Optional[str], Field(description="Override the default organization (ManagedOrganizationId header).", default=None)] = None,
        override_organization_id: Annotated[Optional[str], Field(description="Optional OverrideManagedOrganizationId header.", default=None)] = None,
    ) -> Any:
        """End Maintenance Schedule"""
        body_json = body.model_dump(by_alias=True, exclude_none=True)
        extra_headers = {}
        if override_organization_id is not None:
            extra_headers['OverrideManagedOrganizationId'] = override_organization_id
        client = await get_client()
        return await client.request("PATCH", "/portalapi/MaintenanceMode/MaintenanceModeEndById", organization_id=organization_id, json=body_json, extra_headers=extra_headers or None)

