"""ThreatLocker MCP tools for tag: OnlineDevices.

Generated by scripts/generate_from_spec.py. Do not edit by hand.
"""
from __future__ import annotations

from typing import Annotated, Any, Optional

from fastmcp import FastMCP
from pydantic import Field

from ..client import get_client
from .. import models


def register(mcp: FastMCP) -> None:
    @mcp.tool(name="online_devices_get_by_parameters", description='View Online Devices')
    async def online_devices_get_by_parameters(
        page_number: Annotated[Optional[int], Field(default=None)] = None,
        page_size: Annotated[Optional[int], Field(default=None)] = None,
        organization_id: Annotated[Optional[str], Field(description="Override the default organization (ManagedOrganizationId header).", default=None)] = None,
        override_organization_id: Annotated[Optional[str], Field(description="Optional OverrideManagedOrganizationId header.", default=None)] = None,
    ) -> Any:
        """View Online Devices"""
        params = {"pageNumber": page_number, "pageSize": page_size}
        params = {k: v for k, v in params.items() if v is not None}
        extra_headers = {}
        if override_organization_id is not None:
            extra_headers['OverrideManagedOrganizationId'] = override_organization_id
        client = await get_client()
        return await client.request("GET", "/portalapi/OnlineDevices/OnlineDevicesGetByParameters", organization_id=organization_id, params=params, extra_headers=extra_headers or None)

