"""ThreatLocker MCP tools for tag: Organization.

Generated by scripts/generate_from_spec.py. Do not edit by hand.
"""

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import FastMCP
from pydantic import Field

from ..client import get_client


def register(mcp: FastMCP) -> None:
    @mcp.tool(
        name="list_organizations",
        description="Get Organizations For Move Computers Returns the organizations the current API key can target. Use this FIRST to discover org GUIDs to pass as `organization_id` to other tools. Despite the path name (the endpoint also feeds the portal's 'move computers' org picker), the result is the canonical list of accessible orgs for this key. `searchText` filters by display name; pass an empty string for the full list.",
    )
    async def list_organizations(
        search_text: Annotated[str | None, Field(default=None)] = None,
        organization_id: Annotated[
            str | None,
            Field(
                description="Override the default organization (ManagedOrganizationId header).",
                default=None,
            ),
        ] = None,
        override_organization_id: Annotated[
            str | None,
            Field(description="Optional OverrideManagedOrganizationId header.", default=None),
        ] = None,
    ) -> Any:
        """Get Organizations For Move Computers Returns the organizations the current API key can target. Use this FIRST to discover org GUIDs to pass as `organization_id` to other tools. Despite the path name (the endpoint also feeds the portal's 'move computers' org picker), the result is the canonical list of accessible orgs for this key. `searchText` filters by display name; pass an empty string for the full list."""
        params = {"searchText": search_text}
        params = {k: v for k, v in params.items() if v is not None}
        extra_headers = {}
        if override_organization_id is not None:
            extra_headers["OverrideManagedOrganizationId"] = override_organization_id
        client = await get_client()
        return await client.request(
            "GET",
            "/portalapi/Organization/OrganizationGetForMoveComputers",
            organization_id=organization_id,
            params=params,
            extra_headers=extra_headers or None,
        )
