"""ThreatLocker MCP tools for tag: Report.

Generated by scripts/generate_from_spec.py. Do not edit by hand.
"""
from __future__ import annotations

from typing import Annotated, Any, Optional

from fastmcp import FastMCP
from pydantic import Field

from ..client import get_client
from .. import models


def register(mcp: FastMCP) -> None:
    @mcp.tool(name="report_get_by_organization_id", description='Get report(s) by organization id.')
    async def report_get_by_organization_id(
        organization_id: Annotated[Optional[str], Field(description="Override the default organization (ManagedOrganizationId header).", default=None)] = None,
        override_organization_id: Annotated[Optional[str], Field(description="Optional OverrideManagedOrganizationId header.", default=None)] = None,
    ) -> Any:
        """Get report(s) by organization id."""
        extra_headers = {}
        if override_organization_id is not None:
            extra_headers['OverrideManagedOrganizationId'] = override_organization_id
        client = await get_client()
        return await client.request("GET", "/portalapi/Report/ReportGetByOrganizationId", organization_id=organization_id, extra_headers=extra_headers or None)

