"""ThreatLocker MCP tools for tag: SystemAudit.

Generated by scripts/generate_from_spec.py. Do not edit by hand.
"""

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import FastMCP
from pydantic import Field

from .. import models
from ..client import get_client


def register(mcp: FastMCP) -> None:
    @mcp.tool(
        name="system_audit_get_by_parameters",
        description="Retrieves System Audit records based on specified parameters.",
    )
    async def system_audit_get_by_parameters(
        body: Annotated[models.SystemAuditParametersDto, Field(description="Request body.")],
        organization_id: Annotated[
            str | None,
            Field(
                description="Override the default organization (ManagedOrganizationId header).",
                default=None,
            ),
        ] = None,
        override_organization_id: Annotated[
            str | None,
            Field(description="Optional OverrideManagedOrganizationId header.", default=None),
        ] = None,
    ) -> Any:
        """Retrieves System Audit records based on specified parameters."""
        body_json = body.model_dump(by_alias=True, exclude_none=True)
        extra_headers = {}
        if override_organization_id is not None:
            extra_headers["OverrideManagedOrganizationId"] = override_organization_id
        client = await get_client()
        return await client.request(
            "POST",
            "/portalapi/SystemAudit/SystemAuditGetByParameters",
            organization_id=organization_id,
            json=body_json,
            extra_headers=extra_headers or None,
        )

    @mcp.tool(
        name="system_audit_get_for_health_center",
        description="Retrieves System Audit data for the Health Center, specifically focused on login attempts.",
    )
    async def system_audit_get_for_health_center(
        body: Annotated[models.SystemAuditHealthCenterParams, Field(description="Request body.")],
        organization_id: Annotated[
            str | None,
            Field(
                description="Override the default organization (ManagedOrganizationId header).",
                default=None,
            ),
        ] = None,
        override_organization_id: Annotated[
            str | None,
            Field(description="Optional OverrideManagedOrganizationId header.", default=None),
        ] = None,
    ) -> Any:
        """Retrieves System Audit data for the Health Center, specifically focused on login attempts."""
        body_json = body.model_dump(by_alias=True, exclude_none=True)
        extra_headers = {}
        if override_organization_id is not None:
            extra_headers["OverrideManagedOrganizationId"] = override_organization_id
        client = await get_client()
        return await client.request(
            "POST",
            "/portalapi/SystemAudit/SystemAuditGetForHealthCenter",
            organization_id=organization_id,
            json=body_json,
            extra_headers=extra_headers or None,
        )
