"""ThreatLocker MCP tools for tag: Tag.

Generated by scripts/generate_from_spec.py. Do not edit by hand.
"""

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import FastMCP
from pydantic import Field

from .. import models
from ..client import get_client


def register(mcp: FastMCP) -> None:
    @mcp.tool(name="tag_get_by_id", description="Get Tag by Id.")
    async def tag_get_by_id(
        tag_id: Annotated[str | None, Field(default=None)] = None,
        organization_id: Annotated[
            str | None,
            Field(
                description="Override the default organization (ManagedOrganizationId header).",
                default=None,
            ),
        ] = None,
        override_organization_id: Annotated[
            str | None,
            Field(description="Optional OverrideManagedOrganizationId header.", default=None),
        ] = None,
    ) -> Any:
        """Get Tag by Id."""
        params = {"tagId": tag_id}
        params = {k: v for k, v in params.items() if v is not None}
        extra_headers = {}
        if override_organization_id is not None:
            extra_headers["OverrideManagedOrganizationId"] = override_organization_id
        client = await get_client()
        return await client.request(
            "GET",
            "/portalapi/Tag/TagGetById",
            organization_id=organization_id,
            params=params,
            extra_headers=extra_headers or None,
        )

    @mcp.tool(
        name="tag_get_dropdown_options_by_organization_id", description="Get Tag Dropdown Options."
    )
    async def tag_get_dropdown_options_by_organization_id(
        include_built_ins: bool,
        tag_type: int,
        include_network_tag_in_master: bool,
        organization_id: Annotated[
            str | None,
            Field(
                description="Override the default organization (ManagedOrganizationId header).",
                default=None,
            ),
        ] = None,
        override_organization_id: Annotated[
            str | None,
            Field(description="Optional OverrideManagedOrganizationId header.", default=None),
        ] = None,
    ) -> Any:
        """Get Tag Dropdown Options."""
        params = {
            "includeBuiltIns": include_built_ins,
            "tagType": tag_type,
            "includeNetworkTagInMaster": include_network_tag_in_master,
        }
        params = {k: v for k, v in params.items() if v is not None}
        extra_headers = {}
        if override_organization_id is not None:
            extra_headers["OverrideManagedOrganizationId"] = override_organization_id
        client = await get_client()
        return await client.request(
            "GET",
            "/portalapi/Tag/TagGetDowndownOptionsByOrganizationId",
            organization_id=organization_id,
            params=params,
            extra_headers=extra_headers or None,
        )

    @mcp.tool(
        name="tag_update",
        description="Update Tag. Updates an existing tag. `tagId` (spec-nullable) must be a valid existing tag GUID; passing an empty or omitted `tagId` may cause the server to interpret the request as a new-tag creation. Use `tag_get_dropdown_options_by_organization_id` to discover existing tag GUIDs first. `tagType` enum (verify against tenant): 1=Computer tag, 2=Application tag, 3=Network tag. Sending one of `tagItemsText` / `tagItemsIPv4` / `tagItemsIPv6` replaces (not merges) that list for the tag. NOT YET LIVE-TESTED -- verify behaviour against the dev tenant before relying on it.",
    )
    async def tag_update(
        body: Annotated[models.TagDto, Field(description="Request body.")],
        organization_id: Annotated[
            str | None,
            Field(
                description="Override the default organization (ManagedOrganizationId header).",
                default=None,
            ),
        ] = None,
        override_organization_id: Annotated[
            str | None,
            Field(description="Optional OverrideManagedOrganizationId header.", default=None),
        ] = None,
    ) -> Any:
        """Update Tag. Updates an existing tag. `tagId` (spec-nullable) must be a valid existing tag GUID; passing an empty or omitted `tagId` may cause the server to interpret the request as a new-tag creation. Use `tag_get_dropdown_options_by_organization_id` to discover existing tag GUIDs first. `tagType` enum (verify against tenant): 1=Computer tag, 2=Application tag, 3=Network tag. Sending one of `tagItemsText` / `tagItemsIPv4` / `tagItemsIPv6` replaces (not merges) that list for the tag. NOT YET LIVE-TESTED -- verify behaviour against the dev tenant before relying on it."""
        body_json = body.model_dump(by_alias=True, exclude_none=True)
        extra_headers = {}
        if override_organization_id is not None:
            extra_headers["OverrideManagedOrganizationId"] = override_organization_id
        client = await get_client()
        return await client.request(
            "POST",
            "/portalapi/Tag/TagUpdate",
            organization_id=organization_id,
            json=body_json,
            extra_headers=extra_headers or None,
        )
