"""Pydantic models generated from the ThreatLocker OpenAPI spec.

Do not edit by hand. Regenerate via `python scripts/generate_from_spec.py spec.json`.
"""
from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel, ConfigDict, Field


class ActionLogCreatedByProcessesDto(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    created_by_process: Optional[str] = Field(default=None, alias="createdByProcess")
    count: Optional[int] = Field(default=None)


class Certificate(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    subject: Optional[str] = Field(default=None)
    sha: Optional[str] = Field(default=None)
    value: Optional[str] = Field(default=None)
    valid_cert: Optional[bool] = Field(default=None, alias="validCert")


class OrganizationParentsDto(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    organization_id: Optional[str] = Field(default=None, alias="organizationId")
    display_name: Optional[str] = Field(default=None, alias="displayName")


class Int32ObjectKeyValuePair(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    key: Optional[int] = Field(default=None)
    value: Optional[Any] = Field(default=None)


class ThreatLockerItemDto(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    d: Optional[str] = Field(default=None)
    u: Optional[str] = Field(default=None, description='Username')
    pid: Optional[str] = Field(default=None, description='PolicyID')
    pn: Optional[str] = Field(default=None, description='PolicyName')
    at: Optional[int] = Field(default=None, description='ActionType')
    aid: Optional[int] = Field(default=None, description='ActionID')
    a: Optional[list[Int32ObjectKeyValuePair]] = Field(default=None, description='Attribute')


class EngineRating(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    name: Optional[str] = Field(default=None)
    rating: Optional[str] = Field(default=None)


class ActionLogDto(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    action_log_id: Optional[int] = Field(default=None, alias="actionLogId")
    e_action_log_id: Optional[str] = Field(default=None, alias="eActionLogId")
    organization_id: Optional[str] = Field(default=None, alias="organizationId")
    computer_id: Optional[str] = Field(default=None, alias="computerId")
    date_time: Optional[str] = Field(default=None, alias="dateTime")
    date_time_imported: Optional[str] = Field(default=None, alias="dateTimeImported")
    organization_name: Optional[str] = Field(default=None, alias="organizationName")
    hostname: Optional[str] = Field(default=None)
    username: Optional[str] = Field(default=None)
    full_path: Optional[str] = Field(default=None, alias="fullPath")
    policy_name: Optional[str] = Field(default=None, alias="policyName")
    action_type: Optional[str] = Field(default=None, alias="actionType")
    action_type_id: Optional[int] = Field(default=None, alias="actionTypeId")
    action_id: Optional[int] = Field(default=None, alias="actionId")
    action: Optional[str] = Field(default=None)
    is_monitor_mode: Optional[bool] = Field(default=None, alias="isMonitorMode")
    monitor_mode: Optional[str] = Field(default=None, alias="monitorMode")
    learning_mode_end_date: Optional[str] = Field(default=None, alias="learningModeEndDate")
    policy_id: Optional[str] = Field(default=None, alias="policyId")
    policy_location: Optional[str] = Field(default=None, alias="policyLocation")
    policy_organization_id: Optional[str] = Field(default=None, alias="policyOrganizationId")
    process_id: Optional[int] = Field(default=None, alias="processId")
    process_path: Optional[str] = Field(default=None, alias="processPath")
    hash: Optional[str] = Field(default=None)
    created_by_process: Optional[str] = Field(default=None, alias="createdByProcess")
    data: Optional[str] = Field(default=None)
    remote_presence: Optional[bool] = Field(default=None, alias="remotePresence")
    remote_presence_text: Optional[str] = Field(default=None, alias="remotePresenceText")
    remote_presence_threat_locker_detected: Optional[bool] = Field(default=None, alias="remotePresenceThreatLockerDetected")
    device_type: Optional[str] = Field(default=None, alias="deviceType")
    cert: Optional[str] = Field(default=None)
    certs: Optional[list[str]] = Field(default=None)
    cert_exists: Optional[bool] = Field(default=None, alias="certExists")
    certificates: Optional[list[Certificate]] = Field(default=None)
    cert_text: Optional[str] = Field(default=None, alias="certText")
    organization_parents: Optional[list[OrganizationParentsDto]] = Field(default=None, alias="organizationParents")
    application_organization_id: Optional[str] = Field(default=None, alias="applicationOrganizationId")
    application_is_built_in: Optional[bool] = Field(default=None, alias="applicationIsBuiltIn")
    application_id: Optional[str] = Field(default=None, alias="applicationId")
    application_name: Optional[str] = Field(default=None, alias="applicationName")
    notes: Optional[str] = Field(default=None)
    serial_number: Optional[str] = Field(default=None, alias="serialNumber")
    encryption: Optional[int] = Field(default=None)
    size: Optional[int] = Field(default=None)
    sha256_hash: Optional[str] = Field(default=None, alias="sha256Hash")
    policy_exists: Optional[bool] = Field(default=None, alias="policyExists")
    policy_enabled: Optional[bool] = Field(default=None, alias="policyEnabled")
    storage_policy_exists: Optional[bool] = Field(default=None, alias="storagePolicyExists")
    nac_policy_exists: Optional[bool] = Field(default=None, alias="nacPolicyExists")
    secure_network_policy_exists: Optional[bool] = Field(default=None, alias="secureNetworkPolicyExists")
    tw_policy_exists: Optional[bool] = Field(default=None, alias="twPolicyExists")
    web_control_policy_exists: Optional[bool] = Field(default=None, alias="webControlPolicyExists")
    option_to_request: Optional[bool] = Field(default=None, alias="optionToRequest")
    allow_permit_vendor_button: Optional[bool] = Field(default=None, alias="allowPermitVendorButton")
    effective_action: Optional[str] = Field(default=None, alias="effectiveAction")
    encryption_status: Optional[str] = Field(default=None, alias="encryptionStatus")
    report_missing: Optional[bool] = Field(default=None, alias="reportMissing")
    virus_total_check_name: Optional[str] = Field(default=None, alias="virusTotalCheckName")
    virus_total_check_argument: Optional[str] = Field(default=None, alias="virusTotalCheckArgument")
    os_type: Optional[int] = Field(default=None, alias="osType")
    is_extension: Optional[bool] = Field(default=None, alias="isExtension")
    edge_store_url: Optional[str] = Field(default=None, alias="edgeStoreUrl")
    chrome_store_url: Optional[str] = Field(default=None, alias="chromeStoreUrl")
    firefox_store_url: Optional[str] = Field(default=None, alias="firefoxStoreUrl")
    action_log_created_by_processes: Optional[list[ActionLogCreatedByProcessesDto]] = Field(default=None, alias="actionLogCreatedByProcesses")
    total_count: Optional[int] = Field(default=None, alias="totalCount")
    last_sort_value: Optional[int] = Field(default=None, alias="lastSortValue")
    network_direction: Optional[int] = Field(default=None, alias="networkDirection")
    source_i_p_address: Optional[str] = Field(default=None, alias="sourceIPAddress")
    destination_i_p_address: Optional[str] = Field(default=None, alias="destinationIPAddress")
    group_by_count: Optional[int] = Field(default=None, alias="groupByCount")
    destination_port: Optional[str] = Field(default=None, alias="destinationPort")
    batch_id: Optional[str] = Field(default=None, alias="batchId")
    is_protected_process: Optional[bool] = Field(default=None, alias="isProtectedProcess")
    memory_bytes: Optional[int] = Field(default=None, alias="memoryBytes")
    process_name: Optional[str] = Field(default=None, alias="processName")
    parent_process_id: Optional[int] = Field(default=None, alias="parentProcessId")
    parent_process_name: Optional[str] = Field(default=None, alias="parentProcessName")
    has_view_computer_permission: Optional[bool] = Field(default=None, alias="hasViewComputerPermission")
    allow_file_upload: Optional[bool] = Field(default=None, alias="allowFileUpload")
    can_view_on_system_lookup: Optional[bool] = Field(default=None, alias="canViewOnSystemLookup")
    system_lookup_url: Optional[str] = Field(default=None, alias="systemLookupUrl")
    has_policy_data: Optional[bool] = Field(default=None, alias="hasPolicyData")
    threat_locker_item: Optional[ThreatLockerItemDto] = Field(default=None, alias="threatLockerItem")
    integration_type_id: Optional[str] = Field(default=None, alias="integrationTypeId")
    is_cloud_log: Optional[bool] = Field(default=None, alias="isCloudLog")
    is_cloud_action_type: Optional[bool] = Field(default=None, alias="isCloudActionType")
    threat_severity_level: Optional[str] = Field(default=None, alias="threatSeverityLevel")
    engine_ratings: Optional[list[EngineRating]] = Field(default=None, alias="engineRatings")
    is_virus_total_unavailable: Optional[bool] = Field(default=None, alias="isVirusTotalUnavailable")
    delete_file_request_sent: Optional[bool] = Field(default=None, alias="deleteFileRequestSent")
    is_access_device: Optional[bool] = Field(default=None, alias="isAccessDevice")


class ParamsFieldsDto(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    name: Optional[str] = Field(default=None)
    filter_type: Optional[int] = Field(default=None, alias="filterType")
    field_type: Optional[int] = Field(default=None, alias="fieldType")
    value: Optional[str] = Field(default=None)
    label: Optional[str] = Field(default=None)
    dropdown_label: Optional[str] = Field(default=None, alias="dropdownLabel")
    is_drop_down: Optional[bool] = Field(default=None, alias="isDropDown")
    guid_value: Optional[str] = Field(default=None, alias="guidValue")
    numeric_value: Optional[int] = Field(default=None, alias="numericValue")
    long_value: Optional[int] = Field(default=None, alias="longValue")
    bool_value: Optional[bool] = Field(default=None, alias="boolValue")
    date_time_value: Optional[str] = Field(default=None, alias="dateTimeValue")
    field_attribute_id: Optional[int] = Field(default=None, alias="fieldAttributeId")
    list_value: Optional[list[str]] = Field(default=None, alias="listValue")
    list_guid_value: Optional[list[str]] = Field(default=None, alias="listGuidValue")
    list_numeric_value: Optional[list[int]] = Field(default=None, alias="listNumericValue")
    list_long_value: Optional[list[int]] = Field(default=None, alias="listLongValue")
    date_time_interval: Optional[list[str]] = Field(default=None, alias="dateTimeInterval")


class ActionLogParamsDto(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    action_type: Optional[str] = Field(default=None, alias="actionType")
    source_table_id: Optional[int] = Field(default=None, alias="sourceTableId")
    action_log_id: Optional[int] = Field(default=None, alias="actionLogId")
    policy_id: Optional[str] = Field(default=None, alias="policyId")
    action_id: Optional[int] = Field(default=None, alias="actionId")
    filter: Optional[str] = Field(default=None)
    show_child_organizations: Optional[bool] = Field(default=None, alias="showChildOrganizations")
    simulate_deny: Optional[bool] = Field(default=None, alias="simulateDeny")
    only_true_denies: Optional[bool] = Field(default=None, alias="onlyTrueDenies")
    username: Optional[str] = Field(default=None)
    hostname: Optional[str] = Field(default=None)
    process_id: Optional[int] = Field(default=None, alias="processId")
    full_path: Optional[str] = Field(default=None, alias="fullPath")
    device_type: Optional[str] = Field(default=None, alias="deviceType")
    date_time: Optional[list[str]] = Field(default=None, alias="dateTime")
    group_by: Optional[str] = Field(default=None, alias="groupBy")
    page_number: Optional[int] = Field(default=None, alias="pageNumber")
    page_size: Optional[int] = Field(default=None, alias="pageSize")
    params_fields_dto: Optional[list[ParamsFieldsDto]] = Field(default=None, alias="paramsFieldsDto")
    start_date: Optional[str] = Field(default=None, alias="startDate")
    end_date: Optional[str] = Field(default=None, alias="endDate")
    date_time_last_imported: Optional[str] = Field(default=None, alias="dateTimeLastImported")
    show_total_count: Optional[bool] = Field(default=None, alias="showTotalCount")
    get_new_count: Optional[bool] = Field(default=None, alias="getNewCount")
    export_mode: Optional[bool] = Field(default=None, alias="exportMode")
    total_rows: Optional[int] = Field(default=None, alias="totalRows")
    use_e_id: Optional[bool] = Field(default=None, alias="useEId")
    last_sort_value: Optional[int] = Field(default=None, alias="lastSortValue")
    sort_by: Optional[str] = Field(default=None, alias="sortBy")
    sort_descending: Optional[bool] = Field(default=None, alias="sortDescending")
    group_bys: Optional[list[int]] = Field(default=None, alias="groupBys")
    action_types: Optional[list[str]] = Field(default=None, alias="actionTypes")
    show_known_threats_only: Optional[bool] = Field(default=None, alias="showKnownThreatsOnly")
    has_policy_id: Optional[bool] = Field(default=None, alias="hasPolicyId")


class FilePolicy(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    file_policy_id: Optional[str] = Field(default=None, alias="filePolicyId")
    path: Optional[str] = Field(default=None)
    action: Optional[int] = Field(default=None, description='1 = Permit, 2 = Deny')
    permission: Optional[int] = Field(default=None, description='1 = Read, 2 = Write')


class NetworkPolicy(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    network_policy_id: Optional[str] = Field(default=None, alias="networkPolicyId")
    server: Optional[str] = Field(default=None)
    port: Optional[int] = Field(default=None)
    action: Optional[int] = Field(default=None, description='1 = Permit, 2 = Deny')
    server_display_name: Optional[str] = Field(default=None, alias="serverDisplayName")


class RegistryPolicy(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    registry_policy_id: Optional[str] = Field(default=None, alias="registryPolicyId")
    path: Optional[str] = Field(default=None)
    action: Optional[int] = Field(default=None, description='1 = Permit, 2 = Deny')
    permission: Optional[int] = Field(default=None, description='1 = Read, 2 = Write')


class AssociatedApplicationPolicy(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    name: Optional[str] = Field(default=None)
    application_id: Optional[str] = Field(default=None, alias="applicationId")
    os_type: Optional[int] = Field(default=None, alias="osType")


class AdvRFPolicy(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    hide_custom_rules: Optional[bool] = Field(default=None, alias="hideCustomRules")
    restrict_application_spawning: Optional[bool] = Field(default=None, alias="restrictApplicationSpawning")
    restrict_registry_access: Optional[bool] = Field(default=None, alias="restrictRegistryAccess")
    restrict_file_access: Optional[bool] = Field(default=None, alias="restrictFileAccess")
    restrict_network_access: Optional[bool] = Field(default=None, alias="restrictNetworkAccess")
    restrict_application: Optional[bool] = Field(default=None, alias="restrictApplication")
    rf_file_policy: Optional[list[FilePolicy]] = Field(default=None, alias="rfFilePolicy")
    rf_network_policy: Optional[list[NetworkPolicy]] = Field(default=None, alias="rfNetworkPolicy")
    rf_registry_policy: Optional[list[RegistryPolicy]] = Field(default=None, alias="rfRegistryPolicy")
    rf_associated_application_policy: Optional[list[AssociatedApplicationPolicy]] = Field(default=None, alias="rfAssociatedApplicationPolicy")


UpdateStatus = int


class ApplicationFileDto(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    application_file_id: Optional[int] = Field(default=None, alias="applicationFileId")
    application_id: Optional[str] = Field(default=None, alias="applicationId")
    full_path: Optional[str] = Field(default=None, alias="fullPath")
    cert: Optional[str] = Field(default=None)
    hash: Optional[str] = Field(default=None)
    process_path: Optional[str] = Field(default=None, alias="processPath")
    notes: Optional[str] = Field(default=None)
    installed_by: Optional[str] = Field(default=None, alias="installedBy")
    name: Optional[str] = Field(default=None)
    application_file_details: Optional[str] = Field(default=None, alias="applicationFileDetails")
    key_file: Optional[bool] = Field(default=None, alias="keyFile")
    original_full_path: Optional[str] = Field(default=None, alias="originalFullPath")
    original_cert: Optional[str] = Field(default=None, alias="originalCert")
    original_hash: Optional[str] = Field(default=None, alias="originalHash")
    original_process_path: Optional[str] = Field(default=None, alias="originalProcessPath")
    original_notes: Optional[str] = Field(default=None, alias="originalNotes")
    original_installed_by: Optional[str] = Field(default=None, alias="originalInstalledBy")
    original_key_file: Optional[bool] = Field(default=None, alias="originalKeyFile")
    os_type: Optional[int] = Field(default=None, alias="osType")
    is_hash_only: Optional[bool] = Field(default=None, alias="isHashOnly")
    min_size: Optional[int] = Field(default=None, alias="minSize")
    max_size: Optional[int] = Field(default=None, alias="maxSize")
    update_status: Optional[UpdateStatus] = Field(default=None, alias="updateStatus")
    created_by: Optional[str] = Field(default=None, alias="createdBy")
    application_name: Optional[str] = Field(default=None, alias="applicationName")
    organization_id: Optional[str] = Field(default=None, alias="organizationId")


class ThreatLockerCertDto(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    sha: Optional[str] = Field(default=None)
    subject: Optional[str] = Field(default=None)
    valid_cert: Optional[bool] = Field(default=None, alias="validCert")


class ApplicationMatchParameterDto(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    hash: Optional[str] = Field(default=None)
    sha256: Optional[str] = Field(default=None)
    path: Optional[str] = Field(default=None)
    process_path: Optional[str] = Field(default=None, alias="processPath")
    organization_ids: Optional[list[str]] = Field(default=None, alias="organizationIds")
    certs: Optional[list[ThreatLockerCertDto]] = Field(default=None)
    created_bys: Optional[list[str]] = Field(default=None, alias="createdBys")
    os_type: Optional[int] = Field(default=None, alias="osType")
    filename: Optional[str] = Field(default=None)
    folder: Optional[str] = Field(default=None)
    approval_request_id: Optional[str] = Field(default=None, alias="approvalRequestId")
    built_in_partial_matching_files: Optional[list[ApplicationFileDto]] = Field(default=None, alias="builtInPartialMatchingFiles")


class ApplicationOnlineDto(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    name: Optional[str] = Field(default=None)
    application_name: Optional[str] = Field(default=None, alias="applicationName")
    application_id: Optional[str] = Field(default=None, alias="applicationId")
    organization_id: Optional[str] = Field(default=None, alias="organizationId")
    organization_name: Optional[str] = Field(default=None, alias="organizationName")
    os_type: Optional[int] = Field(default=None, alias="osType")
    suggested_policy_id: Optional[str] = Field(default=None, alias="suggestedPolicyId")
    status: Optional[int] = Field(default=None)
    is_maintained: Optional[bool] = Field(default=None, alias="isMaintained")
    research_application_id: Optional[str] = Field(default=None, alias="researchApplicationId")


class ThreatLockerActionDto(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    fullpath: Optional[str] = Field(default=None)
    policyid: Optional[str] = Field(default=None)
    username: Optional[str] = Field(default=None)
    actionid: Optional[int] = Field(default=None)
    hash: Optional[str] = Field(default=None)
    process_name: Optional[str] = Field(default=None, alias="processName")
    certs: Optional[list[ThreatLockerCertDto]] = Field(default=None)
    application_id: Optional[str] = Field(default=None, alias="applicationId")
    datetime: Optional[str] = Field(default=None)
    log_action: Optional[bool] = Field(default=None, alias="logAction")
    serial_number: Optional[str] = Field(default=None, alias="SerialNumber")
    device_type: Optional[str] = Field(default=None, alias="deviceType")
    action_type: Optional[str] = Field(default=None, alias="actionType")
    size: Optional[int] = Field(default=None)
    process_id: Optional[int] = Field(default=None, alias="processId")
    ring_fence: Optional[bool] = Field(default=None, alias="ringFence")
    policy_name: Optional[str] = Field(default=None, alias="policyName")
    application_name: Optional[str] = Field(default=None, alias="applicationName")
    encryption_status: Optional[int] = Field(default=None, alias="encryptionStatus")
    installed_by: Optional[list[str]] = Field(default=None, alias="installedBy")
    monitor_only: Optional[bool] = Field(default=None, alias="monitorOnly")
    notes: Optional[str] = Field(default=None)
    sha256: Optional[str] = Field(default=None)
    ringfence_policy_id: Optional[str] = Field(default=None, alias="ringfencePolicyId")
    remote_presence: Optional[bool] = Field(default=None, alias="remotePresence")
    organization_id: Optional[str] = Field(default=None, alias="organizationId")
    hostname: Optional[str] = Field(default=None)
    computer_id: Optional[str] = Field(default=None, alias="computerId")
    manufacturer: Optional[str] = Field(default=None)
    os_type: Optional[int] = Field(default=None, alias="osType")
    destination_i_p: Optional[str] = Field(default=None, alias="destinationIP")
    domain_name: Optional[str] = Field(default=None, alias="DomainName")
    organization_name: Optional[str] = Field(default=None, alias="organizationName")


class ApprovalRequestTimerDto(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    approval_request_id: Optional[str] = Field(default=None, alias="approvalRequestId")
    request_date: Optional[str] = Field(default=None, alias="requestDate")
    assigned_date: Optional[str] = Field(default=None, alias="assignedDate")
    escalated_date: Optional[str] = Field(default=None, alias="escalatedDate")
    returned_date: Optional[str] = Field(default=None, alias="returnedDate")
    reassigned_date: Optional[str] = Field(default=None, alias="reassignedDate")
    actioned_date: Optional[str] = Field(default=None, alias="actionedDate")
    total_time_in_seconds: Optional[int] = Field(default=None, alias="totalTimeInSeconds")


class ApprovalRequestDto(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    status_id_escalated_to_m_s_p: Optional[int] = Field(default=None, alias="statusIdEscalatedToMSP")
    status_id_escalated_by_customer: Optional[int] = Field(default=None, alias="statusIdEscalatedByCustomer")
    master_organization_id: Optional[str] = Field(default=None, alias="masterOrganizationId")
    approved_by: Optional[str] = Field(default=None, alias="approvedBy")
    approval_request_id: Optional[str] = Field(default=None, alias="approvalRequestId")
    date_time: Optional[str] = Field(default=None, alias="dateTime")
    path: Optional[str] = Field(default=None)
    hash: Optional[str] = Field(default=None)
    username: Optional[str] = Field(default=None)
    hostname: Optional[str] = Field(default=None)
    status_id: Optional[int] = Field(default=None, alias="statusId")
    computer_id: Optional[str] = Field(default=None, alias="computerId")
    organization_name: Optional[str] = Field(default=None, alias="organizationName")
    json_: Optional[str] = Field(default=None, alias="json")
    ticket_id: Optional[str] = Field(default=None, alias="ticketId")
    requestor: Optional[str] = Field(default=None)
    requestor_reason: Optional[str] = Field(default=None, alias="requestorReason")
    requestor_email_address: Optional[str] = Field(default=None, alias="requestorEmailAddress")
    comments: Optional[str] = Field(default=None)
    action_date: Optional[str] = Field(default=None, alias="actionDate")
    organization_id: Optional[str] = Field(default=None, alias="organizationId")
    multi_level_approval_request_id: Optional[str] = Field(default=None, alias="multiLevelApprovalRequestId")
    approval_number: Optional[int] = Field(default=None, alias="approvalNumber")
    approved_by_tier_level: Optional[int] = Field(default=None, alias="approvedByTierLevel")
    temp_policy_id: Optional[str] = Field(default=None, alias="tempPolicyId")
    policy_id: Optional[str] = Field(default=None, alias="policyId")
    temp_application_id: Optional[str] = Field(default=None, alias="tempApplicationId")
    application_id: Optional[str] = Field(default=None, alias="applicationId")
    multi_level_approval_status_id: Optional[int] = Field(default=None, alias="multiLevelApprovalStatusId")
    initial_approval_tier_level: Optional[int] = Field(default=None, alias="initialApprovalTierLevel")
    approval_count: Optional[int] = Field(default=None, alias="approvalCount")
    pending_tier_level: Optional[int] = Field(default=None, alias="pendingTierLevel")
    has_pending_approval_request: Optional[bool] = Field(default=None, alias="hasPendingApprovalRequest")
    ip_address: Optional[str] = Field(default=None, alias="ipAddress")
    is_assigned: Optional[bool] = Field(default=None, alias="isAssigned")
    assignee_user_id: Optional[str] = Field(default=None, alias="assigneeUserId")
    threat_locker_data_center_id: Optional[str] = Field(default=None, alias="threatLockerDataCenterId")
    instance_name: Optional[str] = Field(default=None, alias="instanceName")
    assignee_username: Optional[str] = Field(default=None, alias="assigneeUsername")
    assignee_first_name: Optional[str] = Field(default=None, alias="assigneeFirstName")
    assignee_lastname: Optional[str] = Field(default=None, alias="assigneeLastname")
    threat_locker_action_dto: Optional[ThreatLockerActionDto] = Field(default=None, alias="threatLockerActionDto")
    notes: Optional[str] = Field(default=None)
    signature: Optional[str] = Field(default=None)
    tl_instructions: Optional[str] = Field(default=None, alias="tlInstructions")
    suggest_custom_rule: Optional[bool] = Field(default=None, alias="suggestCustomRule")
    authorize_for_permit: Optional[bool] = Field(default=None, alias="authorizeForPermit")
    portal_api_url: Optional[str] = Field(default=None, alias="portalApiUrl")
    cyber_hero_management_configured: Optional[bool] = Field(default=None, alias="cyberHeroManagementConfigured")
    max_triggered_start_date: Optional[str] = Field(default=None, alias="maxTriggeredStartDate")
    is_escalated_by_cyber_hero: Optional[bool] = Field(default=None, alias="isEscalatedByCyberHero")
    is_escalated_by_customer: Optional[bool] = Field(default=None, alias="isEscalatedByCustomer")
    ticket_approval_manager: Optional[str] = Field(default=None, alias="ticketApprovalManager")
    show_mfa_challenge: Optional[bool] = Field(default=None, alias="showMfaChallenge")
    show_mfa_registration: Optional[bool] = Field(default=None, alias="showMfaRegistration")
    linked_mfa_user: Optional[str] = Field(default=None, alias="linkedMfaUser")
    serial_number: Optional[str] = Field(default=None, alias="serialNumber")
    approval_request_timer_dto: Optional[ApprovalRequestTimerDto] = Field(default=None, alias="approvalRequestTimerDto")
    can_request_new_built_in: Optional[bool] = Field(default=None, alias="canRequestNewBuiltIn")
    is_assignee_logged_into_master: Optional[bool] = Field(default=None, alias="isAssigneeLoggedIntoMaster")
    retrieved_assignee_username: Optional[bool] = Field(default=None, alias="retrievedAssigneeUsername")
    count: Optional[int] = Field(default=None)


class ApprovalRequestParametersDto(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    status_id: Optional[int] = Field(default=None, alias="statusId")
    search_text: Optional[str] = Field(default=None, alias="searchText")
    user_approval_tier_level: Optional[int] = Field(default=None, alias="userApprovalTierLevel")
    show_current_tier_only: Optional[bool] = Field(default=None, alias="showCurrentTierOnly")
    show_child_organizations: Optional[bool] = Field(default=None, alias="showChildOrganizations")
    request_type_id: Optional[int] = Field(default=None, alias="requestTypeId")
    order_by: Optional[str] = Field(default=None, alias="orderBy")
    is_ascending: Optional[bool] = Field(default=None, alias="isAscending")
    action_type: Optional[list[str]] = Field(default=None, alias="actionType")
    page_size: Optional[int] = Field(default=None, alias="pageSize")
    page_number: Optional[int] = Field(default=None, alias="pageNumber")


class ApprovalRequestUpdateParametersDto(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    approval_request_dtos: Optional[list[ApprovalRequestDto]] = Field(default=None, alias="approvalRequestDtos")
    type_: Optional[str] = Field(default=None, alias="type")
    ignore_subject: Optional[str] = Field(default=None, alias="ignoreSubject")
    ignore_reason: Optional[str] = Field(default=None, alias="ignoreReason")
    response_subject: Optional[str] = Field(default=None, alias="responseSubject")
    response_reason: Optional[str] = Field(default=None, alias="responseReason")
    reject_reason: Optional[str] = Field(default=None, alias="rejectReason")
    is_v_d_i: Optional[bool] = Field(default=None, alias="isVDI")
    notify_on_ignore: Optional[bool] = Field(default=None, alias="notifyOnIgnore")
    notify_on_response: Optional[bool] = Field(default=None, alias="notifyOnResponse")
    using_custom_approvals: Optional[bool] = Field(default=None, alias="usingCustomApprovals")
    allowed_approval_request_dtos: Optional[list[ApprovalRequestDto]] = Field(default=None, alias="allowedApprovalRequestDtos")
    denied_approval_request_dtos: Optional[list[ApprovalRequestDto]] = Field(default=None, alias="deniedApprovalRequestDtos")


class ComputerDataForDisableProtectionDto(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    action: Optional[str] = Field(default=None)
    computer_group_id: Optional[str] = Field(default=None, alias="computerGroupId")
    computer_id: Optional[str] = Field(default=None, alias="computerId")
    computer_name: Optional[str] = Field(default=None, alias="computerName")
    maintenance_end_date: Optional[str] = Field(default=None, alias="maintenanceEndDate")
    organization_id: Optional[str] = Field(default=None, alias="organizationId")
    start_date_time: Optional[str] = Field(default=None, alias="startDateTime")


class ComputerDataForEnableProtectionDto(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    applies_to_type: Optional[str] = Field(default=None, alias="appliesToType")
    computer_id: Optional[str] = Field(default=None, alias="computerId")
    computer_install_date: Optional[str] = Field(default=None, alias="computerInstallDate")
    computer_name: Optional[str] = Field(default=None, alias="computerName")
    maintenance_end_date: Optional[str] = Field(default=None, alias="maintenanceEndDate")
    maintenance_type_id: Optional[int] = Field(default=None, alias="maintenanceTypeId")
    organization_id: Optional[str] = Field(default=None, alias="organizationId")
    start_date_time: Optional[str] = Field(default=None, alias="startDateTime")


class ComputerDataForRescanBaselineDto(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    computer_id: Optional[str] = Field(default=None, alias="computerId")
    organization_id: Optional[str] = Field(default=None, alias="organizationId")
    computer_group_id: Optional[str] = Field(default=None, alias="computerGroupId")
    computer_name: Optional[str] = Field(default=None, alias="computerName")


class ComputerDataForTransferDto(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    computer_group_id: Optional[str] = Field(default=None, alias="computerGroupId")
    computer_id: Optional[str] = Field(default=None, alias="computerId")
    computer_name: Optional[str] = Field(default=None, alias="computerName")
    group: Optional[str] = Field(default=None)
    hostname: Optional[str] = Field(default=None)
    maintenance_type_id: Optional[int] = Field(default=None, alias="maintenanceTypeId")
    operating_system: Optional[str] = Field(default=None, alias="operatingSystem")
    organization: Optional[str] = Field(default=None)
    organization_id: Optional[str] = Field(default=None, alias="organizationId")
    os_type: Optional[int] = Field(default=None, alias="osType")


class ComputerDataForUpdateModeDto(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    action: Optional[str] = Field(default=None)
    computer_id: Optional[str] = Field(default=None, alias="computerId")
    computer_group_id: Optional[str] = Field(default=None, alias="computerGroupId")
    computer_name: Optional[str] = Field(default=None, alias="computerName")
    computer_install_date: Optional[str] = Field(default=None, alias="computerInstallDate")
    is_isolated: Optional[bool] = Field(default=None, alias="isIsolated")
    is_locked_out: Optional[bool] = Field(default=None, alias="isLockedOut")
    last_version_change: Optional[str] = Field(default=None, alias="lastVersionChange")
    maintenance_type_id: Optional[int] = Field(default=None, alias="maintenanceTypeId")
    maintenance_end_date: Optional[str] = Field(default=None, alias="maintenanceEndDate")
    organization_id: Optional[str] = Field(default=None, alias="organizationId")
    os_type: Optional[int] = Field(default=None, alias="osType")
    pending_base_files: Optional[bool] = Field(default=None, alias="pendingBaseFiles")
    threat_locker_version: Optional[str] = Field(default=None, alias="threatLockerVersion")
    threat_locker_version_id: Optional[str] = Field(default=None, alias="threatLockerVersionId")
    threat_locker_version_group: Optional[str] = Field(default=None, alias="threatLockerVersionGroup")
    threat_locker_version_group_id: Optional[str] = Field(default=None, alias="threatLockerVersionGroupId")


class ComputerDisabledProtectionDto(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    computer_detail_dtos: Optional[list[ComputerDataForDisableProtectionDto]] = Field(default=None, alias="computerDetailDtos")
    end_date: Optional[str] = Field(default=None, alias="endDate")
    start_date: Optional[str] = Field(default=None, alias="startDate")
    maintenance_mode_type: Optional[int] = Field(default=None, alias="maintenanceModeType")
    permit_end: Optional[bool] = Field(default=None, alias="permitEnd")
    application_id: Optional[str] = Field(default=None, alias="applicationId")


class ComputerEnableProtectionDto(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    computer_detail_dtos: Optional[list[ComputerDataForEnableProtectionDto]] = Field(default=None, alias="computerDetailDtos")


class ComputerGroupItemDto(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    computer_group_id: Optional[str] = Field(default=None, alias="computerGroupId")
    name: Optional[str] = Field(default=None)
    organization_id: Optional[str] = Field(default=None, alias="organizationId")
    organization_name: Optional[str] = Field(default=None, alias="organizationName")
    default: Optional[bool] = Field(default=None)
    os_type: Optional[int] = Field(default=None, alias="osType")
    is_global: Optional[bool] = Field(default=None, alias="isGlobal")


class ComputerParameterDto(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    search_text: Optional[str] = Field(default=None, alias="searchText")
    computer_group: Optional[str] = Field(default=None, alias="computerGroup")
    order_by: Optional[str] = Field(default=None, alias="orderBy")
    page_size: Optional[int] = Field(default=None, alias="pageSize")
    page_number: Optional[int] = Field(default=None, alias="pageNumber")
    child_organizations: Optional[bool] = Field(default=None, alias="childOrganizations")
    action: Optional[str] = Field(default=None)
    is_ascending: Optional[bool] = Field(default=None, alias="isAscending")
    kind_of_action: Optional[str] = Field(default=None, alias="kindOfAction")
    computer_id: Optional[str] = Field(default=None, alias="computerId")
    show_last_check_in: Optional[bool] = Field(default=None, alias="showLastCheckIn")
    show_deleted: Optional[bool] = Field(default=None, alias="showDeleted")
    search_by: Optional[int] = Field(default=None, alias="searchBy")
    threatlocker_version: Optional[str] = Field(default=None, alias="threatlockerVersion")
    is_export: Optional[bool] = Field(default=None, alias="isExport")


class ComputerRescanBaselineDto(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    computer_detail_dtos: Optional[list[ComputerDataForRescanBaselineDto]] = Field(default=None, alias="computerDetailDtos")
    enable_learning: Optional[bool] = Field(default=None, alias="enableLearning")


class ComputerTransferDto(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    computer_detail_dtos: Optional[list[ComputerDataForTransferDto]] = Field(default=None, alias="computerDetailDtos")
    enable_learning_rescan: Optional[bool] = Field(default=None, alias="enableLearningRescan")
    target_computer_group_id: Optional[str] = Field(default=None, alias="targetComputerGroupId")
    target_organization_id: Optional[str] = Field(default=None, alias="targetOrganizationId")


class ComputerUpdateDto(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    computer_id: Optional[str] = Field(default=None, alias="computerId")
    computer_group_id: Optional[str] = Field(default=None, alias="computerGroupId")
    name: Optional[str] = Field(default=None)
    use_proxy_server: Optional[bool] = Field(default=None, alias="useProxyServer")
    proxy_server_option: Optional[str] = Field(default=None, alias="proxyServerOption")
    proxy_url_entry: Optional[str] = Field(default=None, alias="proxyUrlEntry")
    proxy_u_r_l: Optional[str] = Field(default=None, alias="proxyURL")
    options: Optional[list[str]] = Field(default=None)


class ComputerUpdateMaintenanceModeDto(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    application_id: Optional[str] = Field(default=None, alias="applicationId")
    computer_detail_dto: Optional[ComputerDataForUpdateModeDto] = Field(default=None, alias="computerDetailDto")


class MaintenanceApplicationDto(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    application_id: Optional[str] = Field(default=None, alias="applicationId")
    application_name: Optional[str] = Field(default=None, alias="applicationName")
    create_application_only: Optional[bool] = Field(default=None, alias="createApplicationOnly")
    applies_to_id: Optional[str] = Field(default=None, alias="appliesToId")


class MaintenanceExistingApplicationDto(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    application_id: Optional[str] = Field(default=None, alias="applicationId")
    name: Optional[str] = Field(default=None)


class MaintenanceModeConditionsDto(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    maintenance_mode_condition_type_id: Optional[int] = Field(default=None, alias="maintenanceModeConditionTypeId")
    value: Optional[str] = Field(default=None)


class MaintenanceModeEndDto(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    applies_to_type: Optional[int] = Field(default=None, alias="appliesToType")
    computer_id: Optional[str] = Field(default=None, alias="computerId")
    computer_install_date: Optional[str] = Field(default=None, alias="computerInstallDate")
    end_date_time: Optional[str] = Field(default=None, alias="endDateTime")
    maintenance_mode_id: Optional[str] = Field(default=None, alias="maintenanceModeId")
    maintenance_type_id: Optional[int] = Field(default=None, alias="maintenanceTypeId")
    start_date_time: Optional[str] = Field(default=None, alias="startDateTime")


class MaintenanceModeInsertDto(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    all_users: Optional[bool] = Field(default=None, alias="allUsers")
    automatic_application: Optional[bool] = Field(default=None, alias="automaticApplication")
    automatic_application_type: Optional[int] = Field(default=None, alias="automaticApplicationType")
    computer_id: Optional[str] = Field(default=None, alias="computerId")
    create_new_application: Optional[bool] = Field(default=None, alias="createNewApplication")
    end_date_time: Optional[str] = Field(default=None, alias="endDateTime")
    existing_application: Optional[MaintenanceExistingApplicationDto] = Field(default=None, alias="existingApplication")
    maintenance_type_id: Optional[int] = Field(default=None, alias="maintenanceTypeId")
    new_application: Optional[MaintenanceApplicationDto] = Field(default=None, alias="newApplication")
    permit_end: Optional[bool] = Field(default=None, alias="permitEnd")
    start_date_time: Optional[str] = Field(default=None, alias="startDateTime")
    use_existing_application: Optional[bool] = Field(default=None, alias="useExistingApplication")
    users_list: Optional[list[str]] = Field(default=None, alias="usersList")
    computer_date_time: Optional[str] = Field(default=None, alias="computerDateTime")
    maintenance_mode_conditions: Optional[list[MaintenanceModeConditionsDto]] = Field(default=None, alias="maintenanceModeConditions")
    ticket_number: Optional[str] = Field(default=None, alias="ticketNumber")
    notes: Optional[str] = Field(default=None)


class NetworkExclusionDto(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    policy_id: Optional[str] = Field(default=None, alias="policyId")
    tag_prefix_type_id: Optional[int] = Field(default=None, alias="tagPrefixTypeId")
    value: Optional[str] = Field(default=None)


class PermitAdminNotes(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    ticket: Optional[str] = Field(default=None)
    requestor_email: Optional[str] = Field(default=None, alias="requestorEmail")
    comments: Optional[str] = Field(default=None)


class PermitFileDetails(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    full_path: Optional[str] = Field(default=None, alias="fullPath")
    process_path: Optional[str] = Field(default=None, alias="processPath")
    hash: Optional[str] = Field(default=None)
    certificates: Optional[list[ThreatLockerCertDto]] = Field(default=None)
    created_by_processes: Optional[list[str]] = Field(default=None, alias="createdByProcesses")
    filename: Optional[str] = Field(default=None)
    sha256: Optional[str] = Field(default=None)
    date: Optional[str] = Field(default=None)
    original_hostname: Optional[str] = Field(default=None, alias="originalHostname")
    hostname: Optional[str] = Field(default=None)
    username: Optional[str] = Field(default=None)
    organization_name: Optional[str] = Field(default=None, alias="organizationName")
    policy_name: Optional[str] = Field(default=None, alias="policyName")
    application_name: Optional[str] = Field(default=None, alias="applicationName")
    requestor_reason: Optional[str] = Field(default=None, alias="requestorReason")
    approval_status: Optional[str] = Field(default=None, alias="approvalStatus")
    approval_by: Optional[str] = Field(default=None, alias="approvalBy")
    size: Optional[int] = Field(default=None)


class PermitMatchingApplications(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    has_matching_application: Optional[bool] = Field(default=None, alias="hasMatchingApplication")
    use_matching_application: Optional[bool] = Field(default=None, alias="useMatchingApplication")
    matching_application: Optional[ApplicationOnlineDto] = Field(default=None, alias="matchingApplication")
    use_existing_application: Optional[bool] = Field(default=None, alias="useExistingApplication")
    existing_application: Optional[ApplicationOnlineDto] = Field(default=None, alias="existingApplication")
    use_new_application: Optional[bool] = Field(default=None, alias="useNewApplication")
    new_application_name: Optional[str] = Field(default=None, alias="newApplicationName")


class PolicyManualOption(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    full_path: Optional[str] = Field(default=None, alias="fullPath")
    process_path: Optional[str] = Field(default=None, alias="processPath")
    cert: Optional[str] = Field(default=None)
    hash: Optional[str] = Field(default=None)
    created_by: Optional[str] = Field(default=None, alias="createdBy")
    is_default_option: Optional[bool] = Field(default=None, alias="isDefaultOption")
    disabled: Optional[bool] = Field(default=None)


class PermitPolicyConditions(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    use_existing_policy: Optional[bool] = Field(default=None, alias="useExistingPolicy")
    create_manual_policy: Optional[bool] = Field(default=None, alias="createManualPolicy")
    manual_options: Optional[list[PolicyManualOption]] = Field(default=None, alias="manualOptions")
    rule_id: Optional[int] = Field(default=None, alias="ruleId")
    cert_subjects: Optional[list[str]] = Field(default=None, alias="certSubjects")
    created_by_processes: Optional[list[str]] = Field(default=None, alias="createdByProcesses")
    disable_protection: Optional[bool] = Field(default=None, alias="disableProtection")
    included_additional_files: Optional[list[ActionLogDto]] = Field(default=None, alias="includedAdditionalFiles")


class PermitPolicyLevel(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    can_use_entire_organization: Optional[bool] = Field(default=None, alias="canUseEntireOrganization")
    to_entire_organization: Optional[bool] = Field(default=None, alias="toEntireOrganization")
    to_computer_group: Optional[bool] = Field(default=None, alias="toComputerGroup")
    selected_computer_group: Optional[ComputerGroupItemDto] = Field(default=None, alias="selectedComputerGroup")
    to_computer: Optional[bool] = Field(default=None, alias="toComputer")


class SystemAuditDetails(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    page: Optional[str] = Field(default=None)
    function: Optional[str] = Field(default=None)
    object_id: Optional[str] = Field(default=None, alias="objectId")
    details: Optional[str] = Field(default=None)


class SystemAuditItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    organization_id: Optional[str] = Field(default=None, alias="organizationId")
    user_id: Optional[str] = Field(default=None, alias="userId")
    username: Optional[str] = Field(default=None)
    action: Optional[str] = Field(default=None)
    ip_address: Optional[str] = Field(default=None, alias="ipAddress")
    effective_action: Optional[str] = Field(default=None, alias="effectiveAction")
    details: Optional[SystemAuditDetails] = Field(default=None)
    master_view_only: Optional[bool] = Field(default=None, alias="masterViewOnly")
    date_time: Optional[str] = Field(default=None, alias="dateTime")
    system_audit_id: Optional[str] = Field(default=None, alias="systemAuditId")
    system_audit_object_type_id: Optional[int] = Field(default=None, alias="systemAuditObjectTypeId")
    organization_name: Optional[str] = Field(default=None, alias="organizationName")
    ticket_number: Optional[str] = Field(default=None, alias="ticketNumber")
    notes: Optional[str] = Field(default=None)


class PermitApplicationDto(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    computer_id: Optional[str] = Field(default=None, alias="computerId")
    computer_group_id: Optional[str] = Field(default=None, alias="computerGroupId")
    organization_id: Optional[str] = Field(default=None, alias="organizationId")
    organization_ids: Optional[list[str]] = Field(default=None, alias="organizationIds")
    os_type: Optional[int] = Field(default=None, alias="osType")
    user_instance: Optional[str] = Field(default=None, alias="userInstance")
    approval_request: Optional[ApprovalRequestDto] = Field(default=None, alias="approvalRequest")
    is_from_approval: Optional[bool] = Field(default=None, alias="isFromApproval")
    action_log: Optional[ActionLogDto] = Field(default=None, alias="actionLog")
    is_from_action_log: Optional[bool] = Field(default=None, alias="isFromActionLog")
    action_type: Optional[str] = Field(default=None, alias="actionType")
    is_elevation_request: Optional[bool] = Field(default=None, alias="isElevationRequest")
    is_extension_request: Optional[bool] = Field(default=None, alias="isExtensionRequest")
    edge_store_url: Optional[str] = Field(default=None, alias="edgeStoreUrl")
    chrome_store_url: Optional[str] = Field(default=None, alias="chromeStoreUrl")
    can_view_on_system_lookup: Optional[bool] = Field(default=None, alias="canViewOnSystemLookup")
    system_lookup_url: Optional[str] = Field(default=None, alias="systemLookupUrl")
    can_view_virus_total: Optional[bool] = Field(default=None, alias="canViewVirusTotal")
    virus_total_url: Optional[str] = Field(default=None, alias="virusTotalUrl")
    file_history_checked: Optional[bool] = Field(default=None, alias="fileHistoryChecked")
    suggest_custom_rule: Optional[bool] = Field(default=None, alias="suggestCustomRule")
    file_details: Optional[PermitFileDetails] = Field(default=None, alias="fileDetails")
    matching_applications: Optional[PermitMatchingApplications] = Field(default=None, alias="matchingApplications")
    policy_conditions: Optional[PermitPolicyConditions] = Field(default=None, alias="policyConditions")
    policy_expiration_date: Optional[str] = Field(default=None, alias="policyExpirationDate")
    ringfencing_options: Optional[AdvRFPolicy] = Field(default=None, alias="ringfencingOptions")
    network_exclusions: Optional[list[NetworkExclusionDto]] = Field(default=None, alias="networkExclusions")
    ringfence_action_id: Optional[int] = Field(default=None, alias="ringfenceActionId")
    is_ringfenced: Optional[bool] = Field(default=None, alias="isRingfenced")
    has_ringfencing_as_product: Optional[bool] = Field(default=None, alias="hasRingfencingAsProduct")
    has_elevation: Optional[bool] = Field(default=None, alias="hasElevation")
    organization_has_elevation: Optional[bool] = Field(default=None, alias="organizationHasElevation")
    elevation_status: Optional[int] = Field(default=None, alias="elevationStatus")
    elevation_expiration: Optional[int] = Field(default=None, alias="elevationExpiration")
    elevation_expiration_date: Optional[str] = Field(default=None, alias="elevationExpirationDate")
    policy_level: Optional[PermitPolicyLevel] = Field(default=None, alias="policyLevel")
    admin_notes: Optional[PermitAdminNotes] = Field(default=None, alias="adminNotes")
    application_list: Optional[list[ApplicationOnlineDto]] = Field(default=None, alias="applicationList")
    system_audits: Optional[list[SystemAuditItem]] = Field(default=None, alias="systemAudits")
    allow_t_m_m: Optional[bool] = Field(default=None, alias="allowTMM")
    has_origin_approval_center: Optional[bool] = Field(default=None, alias="hasOriginApprovalCenter")
    response_subject: Optional[str] = Field(default=None, alias="responseSubject")
    response_reason: Optional[str] = Field(default=None, alias="responseReason")
    notify_on_response: Optional[bool] = Field(default=None, alias="notifyOnResponse")
    is_execution_request: Optional[bool] = Field(default=None, alias="isExecutionRequest")


class SystemAuditHealthCenterParams(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    days: Optional[int] = Field(default=None)
    search_text: Optional[str] = Field(default=None, alias="searchText")
    is_logged_in: Optional[bool] = Field(default=None, alias="isLoggedIn")
    after_keys: Optional[dict[str, list[Any]]] = Field(default=None, alias="afterKeys")
    page_size: Optional[int] = Field(default=None, alias="pageSize")
    page_number: Optional[int] = Field(default=None, alias="pageNumber")


class SystemAuditParametersDto(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    email_address: Optional[str] = Field(default=None, alias="emailAddress")
    action: Optional[str] = Field(default=None)
    ip_address: Optional[str] = Field(default=None, alias="ipAddress")
    effective_action: Optional[str] = Field(default=None, alias="effectiveAction")
    details: Optional[str] = Field(default=None)
    search_text: Optional[str] = Field(default=None, alias="searchText")
    ip_addresses: Optional[list[str]] = Field(default=None, alias="ipAddresses")
    object_type_ids: Optional[list[int]] = Field(default=None, alias="objectTypeIds")
    start_date: Optional[str] = Field(default=None, alias="startDate")
    end_date: Optional[str] = Field(default=None, alias="endDate")
    page_size: Optional[int] = Field(default=None, alias="pageSize")
    page_number: Optional[int] = Field(default=None, alias="pageNumber")
    view_child_organizations: Optional[bool] = Field(default=None, alias="viewChildOrganizations")
    object_id: Optional[str] = Field(default=None, alias="objectId")
    actions: Optional[list[str]] = Field(default=None)
    index_name: Optional[str] = Field(default=None, alias="indexName")
    after_keys: Optional[dict[str, list[Any]]] = Field(default=None, alias="afterKeys")
    skip_paging: Optional[bool] = Field(default=None, alias="skipPaging")
    function: Optional[str] = Field(default=None)
    page: Optional[str] = Field(default=None)
    email_addresses: Optional[list[str]] = Field(default=None, alias="emailAddresses")


# Resolve any forward references
ActionLogCreatedByProcessesDto.model_rebuild()
Certificate.model_rebuild()
OrganizationParentsDto.model_rebuild()
Int32ObjectKeyValuePair.model_rebuild()
ThreatLockerItemDto.model_rebuild()
EngineRating.model_rebuild()
ActionLogDto.model_rebuild()
ParamsFieldsDto.model_rebuild()
ActionLogParamsDto.model_rebuild()
FilePolicy.model_rebuild()
NetworkPolicy.model_rebuild()
RegistryPolicy.model_rebuild()
AssociatedApplicationPolicy.model_rebuild()
AdvRFPolicy.model_rebuild()
ApplicationFileDto.model_rebuild()
ThreatLockerCertDto.model_rebuild()
ApplicationMatchParameterDto.model_rebuild()
ApplicationOnlineDto.model_rebuild()
ThreatLockerActionDto.model_rebuild()
ApprovalRequestTimerDto.model_rebuild()
ApprovalRequestDto.model_rebuild()
ApprovalRequestParametersDto.model_rebuild()
ApprovalRequestUpdateParametersDto.model_rebuild()
ComputerDataForDisableProtectionDto.model_rebuild()
ComputerDataForEnableProtectionDto.model_rebuild()
ComputerDataForRescanBaselineDto.model_rebuild()
ComputerDataForTransferDto.model_rebuild()
ComputerDataForUpdateModeDto.model_rebuild()
ComputerDisabledProtectionDto.model_rebuild()
ComputerEnableProtectionDto.model_rebuild()
ComputerGroupItemDto.model_rebuild()
ComputerParameterDto.model_rebuild()
ComputerRescanBaselineDto.model_rebuild()
ComputerTransferDto.model_rebuild()
ComputerUpdateDto.model_rebuild()
ComputerUpdateMaintenanceModeDto.model_rebuild()
MaintenanceApplicationDto.model_rebuild()
MaintenanceExistingApplicationDto.model_rebuild()
MaintenanceModeConditionsDto.model_rebuild()
MaintenanceModeEndDto.model_rebuild()
MaintenanceModeInsertDto.model_rebuild()
NetworkExclusionDto.model_rebuild()
PermitAdminNotes.model_rebuild()
PermitFileDetails.model_rebuild()
PermitMatchingApplications.model_rebuild()
PolicyManualOption.model_rebuild()
PermitPolicyConditions.model_rebuild()
PermitPolicyLevel.model_rebuild()
SystemAuditDetails.model_rebuild()
SystemAuditItem.model_rebuild()
PermitApplicationDto.model_rebuild()
SystemAuditHealthCenterParams.model_rebuild()
SystemAuditParametersDto.model_rebuild()
